[tool.poetry]
name = "levisllmhub"
version = "0.2.5"
description = "My personal LLM hub to connect to web-based LLMs"

readme = "README.md"


packages = [{include = "levisllmhub", from = "src"}]


include = [
    "package.json",
    "package-lock.json",
    "src/levisLLMhub/**/*.js"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
