[tool.poetry]
name = "levisllmhub"
version = "0.3.0"
description = "My personal LLM hub to connect to web-based LLMs"
readme = "README.md"
authors = ["Levente Csibi <csibi.levente14@gmail.com>"]
license = "MIT"

homepage = "https://github.com/leweex95/levisllmhub"
repository = "https://github.com/leweex95/levisllmhub"
documentation = "https://github.com/leweex95/levisllmhub#readme"

keywords = ["LLM", "AI", "Python", "Node.js", "Puppeteer", "Integration"]

packages = [{include = "levisllmhub", from = "src"}]

include = [
    "package.json",
    "package-lock.json",
    "src/levisllmhub/**/*.js"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
