name: Test Email

on:
  workflow_dispatch:   # allows manual trigger

jobs:
  send-test-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send test email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Test Email from GitHub Actions"
          body: "This is a test email from a manually triggered workflow."
          to: your_email@gmail.com
          from: "GitHub Actions <your_email@gmail.com>"
