name: Test Email Failure Trigger

on:
  workflow_dispatch:

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Force failure
        run: exit 1

  send-email-on-failure:
    needs: fail-job
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 [TextGen Github Project] Daily Regression Test Failed"
          html_body: |
            <p style="font-family: 'Roboto', Helvetica, sans-serif; font-size:22px; font-weight:bold; color:red;">
              🚨 Daily Regression Test Failed!
            </p>
            <p style="font-family: 'Roboto', Helvetica, sans-serif; font-size:18px;">
              Check logs: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">
              Workflow Run</a>
            </p>
          to: ${{ secrets.EMAIL_USERNAME }}
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
